In [1]:
from quantrocket import get_prices
prices = get_prices("usstock-1d", start_date="2020-03-01", fields="Close")
closes = prices.loc["Close"] # for intraday databases also isolate a time with .xs
from quantrocket.fundamental import get_sharadar_sp500_reindexed_like
are_in_sp500 = get_sharadar_sp500_reindexed_like(closes)

In [20]:
are_in_sp500

Sid,FIBBG0000018G2,FIBBG000001LS0,FIBBG000001NT5,FIBBG000001NV2,FIBBG000001R98,FIBBG000001RB5,FIBBG000001RC4,FIBBG000001RD3,FIBBG000001RF1,FIBBG000001RG0,...,QI000000252817,QI000000253003,QI000000253488,QI000000254586,QI000000255110,QI000000256332,QI000000256349,QI000000256350,QI000000256351,QI000000256352
Date,,,,,,,,,,,,,,,,,,,,,
2020-03-02,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2020-03-03,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2020-03-04,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2020-03-05,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2020-03-06,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-05-05,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2023-05-08,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2023-05-09,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2023-05-10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2023-05-11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [21]:
import pandas as pd
from quantrocket.fundamental import download_sharadar_sp500
download_sharadar_sp500(filepath_or_buffer="sp500_changes.csv", start_date="2020-03-01")
sp500_changes = pd.read_csv("sp500_changes.csv", parse_dates=["DATE"])
sp500_changes.head()

,Sid,DATE,ACTION,TICKER,NAME,CONTRATICKER,CONTRANAME,NOTE
0,FIBBG000D6L294,2020-03-03,removed,XEC,Cimarex Energy Co,IR,Ingersoll Rand Inc,NaN
1,FIBBG000C46HM9,2020-04-06,removed,M,Macy's Inc,CARR,CARRIER GLOBAL Corp,NaN
2,FIBBG000BSD7C2,2020-04-06,removed,RTN,Raytheon Co,OTIS,Otis Worldwide Corp,NaN
3,FIBBG00RP5HYS8,2020-04-06,added,CARR,CARRIER GLOBAL Corp,M,Macy's Inc,NaN
4,FIBBG00RP60KV0,2020-04-06,added,OTIS,Otis Worldwide Corp,RTN,Raytheon Co,NaN

In [22]:
sp500_changes

,Sid,DATE,ACTION,TICKER,NAME,CONTRATICKER,CONTRANAME,NOTE
0,FIBBG000D6L294,2020-03-03,removed,XEC,Cimarex Energy Co,IR,Ingersoll Rand Inc,NaN
1,FIBBG000C46HM9,2020-04-06,removed,M,Macy's Inc,CARR,CARRIER GLOBAL Corp,NaN
2,FIBBG000BSD7C2,2020-04-06,removed,RTN,Raytheon Co,OTIS,Otis Worldwide Corp,NaN
3,FIBBG00RP5HYS8,2020-04-06,added,CARR,CARRIER GLOBAL Corp,M,Macy's Inc,NaN
4,FIBBG00RP60KV0,2020-04-06,added,OTIS,Otis Worldwide Corp,RTN,Raytheon Co,NaN
...,...,...,...,...,...,...,...,...
102,FIBBG000M6TR37,2023-03-10,removed,SBNY,SIGNATURE BANK CORP,BG,BUNGE LTD,NaN
103,FIBBG000DW76Y6,2023-03-20,added,FICO,FAIR ISAAC CORP,LUMN,LUMEN TECHNOLOGIES INC,NaN
104,FIBBG000BGLRN3,2023-03-20,removed,LUMN,LUMEN TECHNOLOGIES INC,FICO,FAIR ISAAC CORP,NaN
105,FIBBG000BHJWG1,2023-05-04,added,AXON,AXON ENTERPRISE INC,FRCB,FIRST REPUBLIC BANK,NaN
106,FIBBG0019LSQ49,2023-05-04,removed,FRCB,FIRST REPUBLIC BANK,AXON,AXON ENTERPRISE INC,NaN